SfTuts\JobeetBundle\Entity\Category:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: '255'
      unique: true
  lifecycleCallbacks: {  }
