SfTuts\JobeetBundle\Entity\Job:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: IDENTITY
    type:
      type: string
      length: '255'
    company:
      type: string
      length: '255'
      nullable: true
    logo:
      type: string
      length: '255'
    url:
      type: string
      length: '255'
      nullable: true
    position:
      type: string
      length: '255'
      nullable: true
    location:
      type: string
      length: '255'
    description:
      type: string
      length: '4000'
    howToApply:
      type: string
      length: '4000'
      column: how_to_apply
    token:
      type: string
      length: '255'
      unique: true
    isPublic:
      type: boolean
      length: null
      column: is_public
    isActivated:
      type: boolean
      length: null
      column: is_activated
    email:
      type: string
      length: '255'
    createdAt:
      type: datetime
      column: created_at
    expiresAt:
      type: datetime
      column: expires_at
  oneToOne:
    category:
      targetEntity: SfTuts\JobeetBundle\Entity\Category
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        category_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
