Acme\JobeetBundle\Entity\Job:
    type: entity
    table: null
    fields:
        id:
            type: integer
            length: null
            precision: 0
            scale: 0
            nullable: false
            unique: false
            id: true
            generator:
                strategy: IDENTITY
        type:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: false
            unique: false
        company:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: true
            unique: false
        logo:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: false
            unique: false
        url:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: true
            unique: false
        position:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: true
            unique: false
        location:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: false
            unique: false
        description:
            type: string
            length: '4000'
            precision: 0
            scale: 0
            nullable: false
            unique: false
        howToApply:
            type: string
            length: '4000'
            precision: 0
            scale: 0
            nullable: false
            unique: false
            column: how_to_apply
        token:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: false
            unique: true
        is_public:
            type: boolean
            length: null
            precision: 0
            scale: 0
            nullable: false
            unique: false
        isActivated:
            type: boolean
            length: null
            precision: 0
            scale: 0
            nullable: false
            unique: false
            column: is_activated
        email:
            type: string
            length: '255'
            precision: 0
            scale: 0
            nullable: false
            unique: false
        createdAt:
            type: datetime
            length: null
            precision: 0
            scale: 0
            nullable: false
            unique: false
            column: created_at
        expiresAt:
            type: datetime
            length: null
            precision: 0
            scale: 0
            nullable: false
            unique: false
            column: expires_at
    oneToOne:
        category:
            targetEntity: Acme\JobeetBundle\Entity\Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
